### ISSUE TITLE
Bringing more people to the repository

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-cg#18]
Currently, we have only 11 watchers of the repository, even though we get more participation in the calls and also some people who respond to the emails are not watching it. This means that once we send an announcement via the discussions tab, only 11 people will get an email but many more gets emails. We should discuss in an internal meeting how to get more people to watch and thus get the announcements.

**Comment by egekorkan** [comment]
I have added "Please watch our repository" in the presentation templates

**Comment by lmy441900** [comment]
I don't have email enabled for GitHub so there's at most 10 getting emails XD

Nevertheless, I propose this alternative form:

    Subscribe to WoT CG by watching for All Activity on https://github.com/w3c/wot-cg

As 1) people also _subscribe_ to forum notifications and mailing list, and 2) seldom developer ask people to "watch their repository", but most video creators do ask their audiences to "subscribe to their channels". I presume saying _"Please subscribe"_ conveys our meaning in a better way. Putting a screenshot of the dropdown beside is even better.

\* Not "all activities", because it's what it is on GitHub.

**Comment by egekorkan** [comment]
We talked about this in today's office hours and it would be better to not direct people to the repository since anything of importance is communicated via email or discord. There are many PRs etc. that are not of relevance to an outsider. Closing :)
